### ISSUE TITLE
modify and support redhat7.2....

### ISSUE THREAD

**Issue by cloudusers** [arut/linux-tcp-drop#5]
(1)add macro :
#define TCP_DROP_PROC_DIR "test_net"

(2)replace tcp_drop_init with follow code:

static int __init 
tcp_drop_init(void)
{
    printk(KERN_DEBUG "tcp_drop: loading\n");

    struct file_operations proc_fops=
    {   
        .owner =  THIS_MODULE,
        .write=tcp_drop_write_proc,
    };  
    proc_dir = proc_mkdir(TCP_DROP_PROC_DIR, NULL);                                                                                                                             
    if (!proc_dir) {
        printk(KERN_DEBUG "\ncould not create dstp entry in procfs");
        return  -EAGAIN;
    }   

    proc_file = proc_create(TCP_DROP_PROC_FILE, S_IWUSR | S_IWGRP, proc_dir, &proc_fops);

    if (!proc_file) {
        printk(KERN_ERR "tcp_drop: unable to register proc file\n");
        return -ENOMEM;
    }   
    
    return 0;
}

**Comment by cloudusers** [comment]
#############use this
static const struct file_operations proc_fops=
{
	.owner	 = THIS_MODULE,
//	.read	 = seq_read,
//	.llseek	 = seq_lseek,
	write   : tcp_drop_write_proc,
//	.release = single_release_net
};

    static int __init 
tcp_drop_init(void)
{
    static struct proc_dir_entry *res;

    printk(KERN_DEBUG "tcp_drop: loading\n");

	res = proc_create(TCP_DROP_PROC, 
			S_IWUSR | S_IWGRP, 
#ifdef CONFIG_NET_NS
			init_net.
#endif
			proc_net, 
			&proc_fops);
	/*
    res = create_proc_entry(TCP_DROP_PROC, S_IWUSR | S_IWGRP, 
#ifdef CONFIG_NET_NS
            init_net.
#endif
            proc_net);
	*/

    if (!res) {
        printk(KERN_ERR "tcp_drop: unable to register proc file\n");
        return -ENOMEM;
    }

    //res->write_proc = tcp_drop_write_proc;

    return 0;
}

**Comment by cloudusers** [comment]
because in redhat7
there is not exist create_proc_entry() but only proc_create()
so , replace it

**Comment by loupipalien** [comment]
@cloudusers it works, thx :+1:

**Comment by loupipalien** [comment]
@cloudusers it works, thx :+1:
